#!/usr/bin/env ruby

emcc_path = `which emcc`.split("\n").first

if (!emcc_path)
  puts "Error: Please ensure you have emscripten installed and available on the $PATH.\n\n  emcc: #{emcc_path || 'Not found! Do you need to source emsdk_env.sh?'}"
  exit 1
end

`mkdir -p build`
Dir.chdir("build")

`cp #{__dir__}/../src/c/bindings.c bindings.c`

exported_methods = `cat bindings.c | grep ^EXPORT`.split("\n")
exported_methods.map! { |line| line.split(" ").drop(2).first.split("(").first }

formatted_exported_methods =  "[#{exported_methods.map { |m| "'_#{m}'" }.join(", ")}]"

puts "Compiling to Wasm..."
`
  emcc \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s EXPORTED_FUNCTIONS="#{formatted_exported_methods}" \
    -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
    -s WASM=1 \
    -Oz \
    -gsource-map \
    --source-map-base $PWD/build \
    -I #{__dir__}/../mruby/include \
    bindings.c \
    #{__dir__}/../mruby/build/emscripten/lib/libmruby_core.a \
    #{__dir__}/../mruby/build/emscripten/lib/libmruby.a \
    -o bundle.js
`

`rm bindings.c`
puts "Compiled to build/"
