#!/usr/bin/env ruby

emcc_path = `which emcc`.split("\n").first

if (!emcc_path)
  puts "Error: Please ensure you have emscripten installed and available on the $PATH.\n\n  emcc: #{emcc_path || 'Not found! Do you need to source emsdk_env.sh?'}"
  exit 1
end

`mkdir -p build`
Dir.chdir("build")

`cp #{__dir__}/../main.c main.c`

puts "Compiling to Wasm..."
`
  emcc \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s EXPORTED_FUNCTIONS="['_main', '_render', '_dispatch', '_event', '_load', '_eval', '_print_backtrace', '_handle_callback', '_cleanup_reference', '_get_ruby_reference_type', '_get_ruby_reference_number', '_get_ruby_reference_string', '_load_ruby']" \
    -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
    -s WASM=1 \
    -Oz \
    -g4 \
    --source-map-base $PWD/build \
    -I #{__dir__}/../mruby/include \
    main.c \
    #{__dir__}/../mruby/build/emscripten/lib/libmruby_core.a \
    #{__dir__}/../mruby/build/emscripten/lib/libmruby.a \
    -o bundle.js
`

`rm main.c`
puts "Compiled to build/"
